### ISSUE TITLE
compatibility with Erlang 17

### ISSUE THREAD

**Issue by benoitc** [basho/eleveldb#114]
eleveldb is not compatible with erlang 17 right now

cuttlefish `rebar.config` needs to be updated to build with it but tests are still failing after the update. (`iterator_db_close_test` fails with a segmentation fault on ubuntu 14.04).

**Comment by benoitc** [comment]
Just a quick note but the segmentation fault is not reproducible every time.

**Comment by matthewvon** [comment]
iterator_db_close_test fault is known.  I am addressing it later today in branch mv-tuning7.

**Comment by matthewvon** [comment]
I am told Erlang 17 is intentionally blocked (disallowed).  There are issues getting all of Riak to build "primarily due to some renaming of some types".  The issue is release timing.  Basho's core Erlang developers are focused on the Riak 2.0 release.  Erlang 17 compatibility will come after that release.
