### ISSUE TITLE
leveldb_repair refused to repair eleveldb, potentially out of sync with eleveldb:repair [JIRA: RIAK-2171]

### ISSUE THREAD

**Issue by define-null** [basho/eleveldb#128]
We are using eleveldb 2.0.0. After sudden server reboot one of our eleveldb instances became broken.

leveldb_repair refused to repair it:

``` bash
sudo /usr/lib/project/lib/eleveldb-2.0.0/priv/leveldb_repair /var/lib/project/data/some_base
Repair of /var/lib/project/data/some_base failed.
```

First attempt lasted for several minutes and simply abort with message above. Another one aborted immediately.

I tried

``` bash
Eshell V6.1 (abort with ^G)
1> {ok, D} = eleveldb:open("/var/lib/project/data/some_base", []).
** exception error: no match of right hand side value {error,{db_open,"Corruption: truncated record at end of file"}}
```

Eventually I tried:

``` erlang
eleveldb:repair("/var/lib/project/data/some_base", []).
```

and it fixed the situation. I guess leveldb_repair and eleveldb:repair are out of sync?

**Comment by matthewvon** [comment]
I would assume you manually built leveldb_repair.  The likely cause is that the build for leveldb_repair will seldom automatically include the Snappy compression.  The LOG file in the leveldb subdirectory would have the detail of the error to verify.

That said, there has long been the plan to build these tools and ship them with the product so that end users do not require perfect build environments.  It is just one of those low priority items that has yet to happen.
